name: pre_merge
on:
  pull_request_target:
    branches:
      - qcom-next-staging
  pull_request:
    branches:
      - qcom-next-staging

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      docker_image: kmake-image:latest

  test:
    needs: [build]
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      docker_image: kmake-image:latest